### ISSUE TITLE
Feature request: provide an alternative way to display the QR code on the web interface

### ISSUE THREAD

**Issue by monyxie** [shivensinha4/qr-fileshare#1]
Displaying QR codes in the console/terminal doesn't always work out very well. For example, this is qr-fileshare being run in cmd:
![qr-fileshare-under-cmd](https://user-images.githubusercontent.com/703164/49271182-8dc4c980-f4a7-11e8-864d-ff527a81d59c.png)
And this is in PHPStorm:
![qr-fileshare-under-phpstorm](https://user-images.githubusercontent.com/703164/49271533-16903500-f4a9-11e8-898b-d2ba944182f2.png)
My QR scanner barely recognizes the first one and needless to say, the second one doesn't work at all.

We can workaround this by providing an alternative way to display the QR code on the web interface.

**Comment by shivensinha4** [comment]
Thanks for pointing that out, and suggesting the workaround. I've implemented it. Update the package using `npm i -g qr-fileshare`, and it should now work.

![qr-fileshare](https://user-images.githubusercontent.com/19777714/49282902-501b6d00-f4b6-11e8-9973-c81ba111da65.png)

**Comment by monyxie** [comment]
That was quick! Thank you!
I installed the new version, but I got this error when I run it:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'client/src/generated_qr.svg'
```

**Comment by shivensinha4** [comment]
Sorry for the problems. I've released an update. Does it work now?

**Comment by monyxie** [comment]
It works great now. Thank you!
