### ISSUE TITLE
Bug: TypeError: storage.clear is not a function

### ISSUE THREAD

**Issue by joeberetta** [shivensinha4/qr-fileshare#2]
### Error
```bash
C:\Users\USERNAME\AppData\Roaming\npm\node_modules\qr-fileshare\index.js:49
storage.clear();
TypeError: storage.clear is not a function
at Server.<anonymous> (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\qr-fileshare\index.js:49:13)
```
### Cause of error
You use  latest (^3.0.1) version of [node persist](https://www.npmjs.com/package/node-persist) as dependency.

As noted in [changelog of v3.0.0](https://www.npmjs.com/package/node-persist#300-change-logs) all operations are asynchronous
> All the *Sync functions were removed, every operation is now asynchronous

### Solution
Rewrite it:
```javascript
// index.js
  let server = app.listen(...options, () => {
    const serverAcquiredAddress = `http://${server.address().address}:${server.address().port}`;
    console.log(serverAcquiredAddress);
    displayQrCode(serverAcquiredAddress);
    !devEnv && opn(serverAcquiredAddress);
    app.locals.fileCount = 0; // Store the number of files, useful for generating new ids
    storage.init();
    storage.clear();
    configureApp();
    configureSocketServer(server);
  });
```
As shown below:
```javascript
// index.js
  let server = app.listen(...options, async () => {
    const serverAcquiredAddress = `http://${server.address().address}:${server.address().port}`;
    console.log(serverAcquiredAddress);
    displayQrCode(serverAcquiredAddress);
    !devEnv && opn(serverAcquiredAddress);
    app.locals.fileCount = 0; // Store the number of files, useful for generating new ids
    await storage.init();
    await storage.clear();
    configureApp();
    configureSocketServer(server);
  });
```

**Comment by shivensinha4** [comment]
Yup, easily reproduced. Would you want to go ahead and open a PR?

**Comment by johntomcy** [comment]
Created a pull request as suggested by user joeberetta.
I also had the same issue, so just copied his suggested code and created the PR as told by the author.
Note: I am new to Github and haven't contributed anything so far. So don't know much etiquette. I thought of helping out. I dont need any credit as i dont deserve it. The fix credit should go to joeberetta. I just created a PR and that too i am not sure how correct the code is as i didn't test it in local.

**Comment by joeberetta** [comment]
I would close issue.
@shivensinha4 you would merge PR from @johntomcy
